services:
  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - license=basic
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
    networks:
      - network

  kibana:
    image: kibana:7.17.0
    environment:
      - elasticsearch.hosts=["http://localhost:9200"]
    ports:
      - "5601:5601"
    networks:
      - network
    depends_on:
      - elasticsearch

  neo4j:
    image: neo4j:4.3.3
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474"
      - "7687:7687"

  postgres:
    image: ramsrib/pgvector:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pgvector_db
    ports:
      - "5432:5432"

networks:
  network:
    driver: bridge